version: '3.8'

services:
  fastapi-app:
    build: .
    container_name: fastapi-app
    depends_on:
      - redis
    networks:
      - app-network

  redis:
    image: redis:latest
    container_name: redis
    networks:
      - app-network

networks:
  app-network: